version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./portfolio-client
    volumes:
      - /client/node_modules
      - ./portfolio-client:/client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/api
  dbserver:
    build:
      dockerfile: Dockerfile.dev
      context: ./db-server
    volumes:
      - /db-server/node_modules
      - ./db-server:/db-server
  router:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./router
    ports:
      - "5000:80"
