FROM node:alpine as builder

WORKDIR /portfolio-client

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx

COPY --from=builder /portfolio-client/build/ /usr/share/nginx/html

CMD /bin/bash -c "envsubst '\$PORT' < ./nginx/default.heroku.conf > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'