FROM node:alpine as builder

WORKDIR /portfolio-client

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /portfolio-client/build/ /usr/share/nginx/html
